modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/aqariio/fowl-play/issues"
license = "MIT"

[[mods]]
modId = "fowlplay"
version = "${version}"
displayName = "Fowl Play"
description = '''
Just smile and wave, boys. Smile and wave.
'''
authors = "aqario"
credits = "Penguin60, Disketaa, owen233666"
logoFile = "assets/fowlplay/icon.png"
displayURL = "https://modrinth.com/mod/fowlplay"

[[dependencies.fowlplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[${sbl_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[${yacl_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "fowlplay.common.mixins.json"

[[mixins]]
config = "fowlplay.forge.mixins.json"
