# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft
deps.minecraft = 1.21.1
deps.parchment = 2024.11.17

# Fabric
deps.fabric_loader = 0.16.5
deps.fabric_api = 0.116.7+1.21.1

# NeoForge
deps.neoforge = 21.1.210

# Plugins
deps.fabric_loom = 1.17-SNAPSHOT

# Dependencies
deps.cloth_config = 15.0.140
deps.debugutils = 1.21-1.0.6
deps.fabric_language_kotlin = 1.13.2+kotlin.2.1.20
deps.fabric_permissions_api = 0.3.1
deps.kotlin_for_forge = 5.10.0
deps.modmenu = 11.0.3
deps.nbt_autocomplete = 1.3.10
deps.observable = 5.4.4
deps.sbl = 1.16.11
deps.spark = 1.10.109
deps.suggestion_tweaker = 1.20.6-1.5.2
deps.yacl = 3.6.5+1.21.1