# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Project
mod_version = 1.1.0
maven_group = aqario.fowlplay
mod_id = fowlplay
enabled_platforms = fabric,neoforge

# Minecraft
minecraft_version = 1.21.10
parchment_mappings_version = 1.21.10:2025.10.12

# Fabric
fabric_loader_version = 0.18.1
fabric_api_version = 0.138.3+1.21.10

# NeoForge
neoforge_version = 21.10.64

# Plugins
architectury_loom_version = 1.13-SNAPSHOT
architectury_plugin_version = 3.4-SNAPSHOT

# Dependencies
architectury_version = 18.0.8
cloth_config_version = 20.0.149
debugutils_version = 1.21.9-1.0.9
fabric_language_kotlin_version = 1.13.7+kotlin.2.2.21
fabric_permissions_api_version = 0.5.0
kotlin_for_forge_version = 6.0.0
modmenu_version = 16.0.0-rc.1
nbt_autocomplete_version = 1.3.13
observable_version = 5.4.4
sbl_version = 1.16.11
spark_version = 1.10.152
suggestion_tweaker_version = 1.20.6-1.5.2
yacl_version = 3.8.0+1.21.9