modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/aqariio/fowl-play/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "Fowl Play"
description = '''
Just smile and wave, boys. Smile and wave.
'''
authors = "aqario"
credits = "Penguin60, Disketaa, owen233666, sanduicheirainox, Gnom1112, xz123456xz, sunbatheproductions"
logoFile = "assets/fowlplay/icon.png"
displayURL = "https://modrinth.com/mod/fowlplay"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[${arch},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[${sbl},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[${yacl},)"
ordering = "NONE"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[mc-publish]
dependencies = [
    "architectury-api(required)",
    "yacl(required)",
]