modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/aqariio/Fowl-Play/issues"

[properties]
"connector:placeholder" = true

[[mods]]
modId = "fowlplay"
version = "${version}"
displayName = "Fowl Play"
description = '''
Just smile and wave, boys. Smile and wave.
'''
logoFile = "assets/fowlplay/icon.png"
authors = "aqario"
credits = "Penguin60, Disketaa, owen233666"
displayURL = "https://modrinth.com/mod/fowlplay"

[[dependencies.fowlplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.123,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "fabric_api"
type = "required"
versionRange = "[${fabric_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "connector"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "sinytra1343"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"