name: Bug / Crash Report
description: Report a bug or crash
title: "[Bug] "
labels: [ "bug" ]
assignees:
  - aqariio
body:
  - type: markdown
    attributes:
      value: |
        <br/>
        
        ### ‼️Read before making an issue‼️
        
        1. Check that the problem isn't answered in the **"Important Information"** section of the [mod description](https://modrinth.com/mod/fowlplay).
        2. If you are using Forge or NeoForge, make sure this isn't a problem with Sinytra Connector.
        3. Use the search function to confirm your issue doesn't already exist.
        4. Make sure you are on the latest version of the mod.
        
        --------------------------------------------------

  - type: dropdown
    id: version
    attributes:
      label: "Version"
      options:
        - 1.21.1 - Fabric
        - 1.21.1 - NeoForge
        - 1.20.1 - Fabric
        - 1.20.1 - Forge
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br/>
        
        **Add a Description:**
        
        - Clearly describe what the issue is and how to reproduce it (if possible)
        - Include the latest log if the issue causes a crash (found in <instance>/logs/latest.log)
        - Screenshots and videos are very helpful!

  - type: textarea
    id: description
    attributes:
      label: "Description"
    validations:
      required: true