name: Bug Report
description: Report a bug or crash
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        **Consider the following before continuing:**
        
        1. Check that the problem isn't answered in the "Important Information" section of the mod description.
        2. If you are using Forge or NeoForge, make sure this isn't a problem with Sinytra Connector.
        3. Use the search function to confirm there isn't an existing issue.
        4. Make sure you are on the latest version of the mod.

  - type: dropdown
    id: version
    attributes:
      label: Version and loader
      options:
        - 1.21.1 - Fabric
        - 1.21.1 - NeoForge
        - 1.20.1 - Fabric
        - 1.20.1 - Forge
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Issue Description"
      description: "Describe the problem you are experiencing"
      placeholder: "
      - Clearly describe what the problem is, and how to reproduce it (if possible)\n
      - Include a log if the issue causes a crash (found in .minecraft/logs)\n
      - Screenshots and videos are very helpful!
      "
    validations:
      required: true