modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/aqariio/fowl-play/issues"
license = "MIT"

[[mods]]
modId = "fowlplay"
version = "${version}"
displayName = "Fowl Play"
authors = "aqario"
description = '''
Just smile and wave, boys. Smile and wave.
'''
logoFile = "assets/fowlplay/icon.png"

[[dependencies.fowlplay]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fowlplay]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "fowlplay.mixins.json"
