name: "Publish Branch"

on:
    workflow_call:
        inputs:
            branch:
                description: "Branches"
                required: true
                type: string
permissions: { }

jobs:
    publish:
        runs-on: ubuntu-latest
        name: "Publish ${{ inputs.branch }}"
        timeout-minutes: 30
        permissions:
            pull-requests: read
            contents: write

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.branch }}
                    fetch-depth: 0

            -   name: "Setup Java"
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin

            -   name: "Setup Gradle"
                uses: gradle/actions/setup-gradle@v4
                with:
                    cache-read-only: true
                    gradle-version: wrapper

            -   name: "Parse mod properties"
                id: mod-properties
                run: ./.github/scripts/parse-mod-properties.sh

            -   name: "Parse changelog"
                run: ./.github/scripts/parse-changelog.sh ${{ steps.mod-properties.outputs.MOD_VERSION }}

            -   name: "Publish"
                run: ./gradlew publishMods
                env:
                    CURSEFORGE_ID: ${{ vars.CURSEFORGE_ID }}
                    CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
                    MODRINTH_ID: ${{ vars.MODRINTH_ID }}
                    MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}